name: EeroControl

options:
  bundleIdPrefix: me.davelindon
  deploymentTarget:
    macOS: "13.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: NO

targets:
  EeroControl:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
        excludes:
          - EeroControl.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.davelindon.eerocontrol
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/EeroControl.entitlements
        ENABLE_HARDENED_RUNTIME: YES
    dependencies: []
    scheme:
      testTargets:
        - EeroControlTests

  EeroControlTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.davelindon.eerocontrol.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: EeroControl
